-- MySQL Script generated by MySQL Workbench
-- 11/10/14 22:53:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comentariosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comentariosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comentariosdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `comentariosdb` ;

-- -----------------------------------------------------
-- Table `comentariosdb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comentariosdb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `comentariosdb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comentariosdb`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comentariosdb`.`comentario` ;

CREATE TABLE IF NOT EXISTS `comentariosdb`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `idpelicula` INT NOT NULL,
  `comentario` VARCHAR(500) NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_comentario_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `comentariosdb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
